import styles from "./about.module.css";
import MouseImageTrail from "../../components/effects/mouse-image-trail";

export default function AboutUs() {
  return (
    <>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.heading}>about us</h1>
          <p className={styles.paragraph}>
            FLAVORS IS A CULTURAL CLUB DEDICATED TO EXPERIENCING DIFFERENT CULTURES THROUGH TASTE, CUISINE, AND CONVERSATION.
            FOOD IS NOT ONLY A WINDOW INTO UNDERSTANDING CULTURE BUT ALSO AN INCREDIBLE WAY TO BUILD MEANINGFUL RELATIONSHIPS. 
            OUR GOAL IS TO "BREAK BREAD" WITH OUR PEERS, FOSTERING CONNECTIONS THROUGH A SHARED ENTHUSIASM FOR EXPLORING DIVERSE CUISINES AND CULTURES. 
            TRYING NEW FOODS CAN BE AN ADVENTURE—SOMETIMES DAUNTING BUT ALWAYS EXCITING—AND WE AIM TO INSPIRE OPEN-MINDEDNESS IN EMBRACING THESE EXPERIENCES.
          </p>
          <p className={styles.paragraph}>
            IN A WORLD INCREASINGLY DIVIDED BY LABELS, FLAVORS STRIVES TO CREATE AN OPEN ATMOSPHERE WHERE PEOPLE CAN TRANSCEND CULTURAL BARRIERS, 
            ENGAGE IN MEANINGFUL DIALOGUE, AND TRULY GET TO KNOW ONE ANOTHER. 
            BY BREAKING THE ICE, WE HOPE TO SPARK CONVERSATIONS THAT BRING TOGETHER PEOPLE FROM ALL WALKS OF LIFE TO SHARE THEIR STORIES, 
            PASSIONS, AND VALUES, AND SIMPLY ENJOY GREAT CONVERSATIONS.
          </p>
        </main>
      </div>
    </>
  );
}